"""Equivariant layer constrained to the COMMUTANT of a (discovered) Lie generator.

Given a generator L in gl(n) discovered by core/symmetry_discovery.py, a linear map W that
commutes with L -- [W, L] = 0 -- is exactly equivariant to the one-parameter group exp(theta*L):
W(exp(theta L) x) = exp(theta L)(W x). This is the precise realization of "weight-sharing under
the group generated by L" (primitive 4), and it is the quantum-mechanical statement that W is a
conserved quantity of the symmetry.

We parameterize W directly in the commutant subspace: find an orthonormal basis {B_1..B_K} of
{W : [W,L]=0} (the nullspace of W -> LW - WL), then set W = sum_k c_k B_k with the c_k the only
free parameters. This is dimension-AGNOSTIC: it works for a 2D rotation, a 3D axis rotation, a 4D
double-rotation, a Lorentz boost, etc., with no special-casing -- the commutant computation is the
same linear algebra in every dimension. This directly answers the higher-dimensional case: an
n-dimensional generator gives an n x n commutant layer with no bespoke handling.

The layer maps R^n -> R^n (the symmetry acts on the coordinate space). For a hidden width larger
than n, we equivariantly lift by using `channels` independent commutant maps sharing the same
constraint (a direct sum of equivariant blocks), then an equivariant readout.

STATUS (documented, validated, but not on the live AllGraph path). The single-generator commutant
layer of the Family-2 discovery->architecture arc (used by core/equivariant_supergraph.py). Its
commutant/nullspace construction was GENERALIZED by core/emlp_layer.py (equivariant_basis = null of the
Lie-derivative operator, built from a SET of generators, with direct-sum reps and metric bilinear
invariants), and it is that emlp_layer path -- not this module -- that the live AllGraph controller
deploys as the `generated_equivariant` contract. Retained as the documented, validated Family-2
realization; exported but no longer invoked by fit(). See core/equivariant_supergraph.py.
"""
from __future__ import annotations
import numpy as np
import torch
import torch.nn as nn


def commutant_basis(L, tol=1e-8):
    """Orthonormal basis of {W in R^{n x n} : [W, L] = 0}, returned as a (K, n, n) array.

    [W,L] = WL - LW. Vectorizing (row-major): vec(WL) = (L^T kron I) vec(W),
    vec(LW) = (I kron L) vec(W), so vec([W,L]) = (L^T kron I - I kron L) vec(W). The commutant is
    the nullspace of that (n^2 x n^2) matrix.
    """
    L = np.asarray(L, dtype=np.float64)
    n = L.shape[0]
    I = np.eye(n)
    A = np.kron(L.T, I) - np.kron(I, L)          # A vec(W) = vec([W,L])
    U, S, Vt = np.linalg.svd(A)
    thresh = tol * max(1.0, S.max() if S.size else 1.0)
    # nullspace = right-singular vectors whose singular value is ~0. SVD returns S of length
    # min(rows,cols)=n^2; any index with S<=thresh, plus the fully-zero tail, is nullspace.
    null_idx = [i for i in range(len(S)) if S[i] <= thresh]
    basis = np.stack([Vt[i].reshape(n, n) for i in null_idx], axis=0) if null_idx else \
        np.zeros((0, n, n))
    return basis


class EquivariantLayer(nn.Module):
    """Linear map R^(channels*n) -> R^(channels*n) constrained to be equivariant to exp(theta*L).

    The input is treated as `channels` groups of n coordinates; each output channel is an
    equivariant (commutant) mixture of the input channels. Concretely, for input channels
    {x_a in R^n} and output channels {y_b in R^n}, y_b = sum_a W_{ba} x_a with every W_{ba} in
    the commutant of L. This is equivariant because a direct sum of commutant maps commutes with
    the block-diagonal action diag(exp(theta L), ..).
    """

    def __init__(self, L, in_channels=1, out_channels=1, seed=0):
        super().__init__()
        basis = commutant_basis(L)                       # (K, n, n)
        self.n = int(L.shape[0])
        self.K = int(basis.shape[0])
        self.in_ch, self.out_ch = in_channels, out_channels
        # register the (fixed) commutant basis
        self.register_buffer("basis", torch.tensor(basis, dtype=torch.float32))
        # free coefficients: one length-K vector per (out_channel, in_channel) block
        torch.manual_seed(seed)
        self.coeff = nn.Parameter(0.1 * torch.randn(out_channels, in_channels, max(self.K, 1)))
        if self.K == 0:
            # degenerate: no nontrivial commutant (only happens if L is generic full-rank with
            # trivial centralizer); fall back to identity-scaled to keep the layer usable.
            self.register_buffer("_fallback", torch.eye(self.n))

    def weight_blocks(self):
        """Return the (out_ch, in_ch, n, n) constrained weight tensor W_{ba} in commutant(L)."""
        if self.K == 0:
            return self._fallback.expand(self.out_ch, self.in_ch, self.n, self.n)
        # W_{ba} = sum_k coeff[b,a,k] * basis[k]
        return torch.einsum("bak,kij->baij", self.coeff, self.basis)

    def forward(self, x):
        # x: (batch, in_channels, n)  ->  (batch, out_channels, n)
        # y_{n,b,i} = sum_{a,j} W_{b,a,i,j} x_{n,a,j}
        W = self.weight_blocks()                          # (out, in, n, n)
        return torch.einsum("baij,naj->nbi", W, x)

    def equivariance_error(self, L, theta=0.5, n_samples=64):
        """Diagnostic: max |W(Rx) - R(Wx)| for R=exp(theta L), single input channel."""
        with torch.no_grad():
            Lt = torch.tensor(np.asarray(L), dtype=torch.float32)
            R = expm_series(theta * Lt)
            x = torch.randn(n_samples, self.in_ch, self.n)
            Rx = torch.einsum("ij,ncj->nci", R, x)
            lhs = self.forward(Rx)
            rhs = torch.einsum("ij,ncj->nci", R, self.forward(x))
            return float((lhs - rhs).abs().max())


def expm_series(A, terms=30):
    """Matrix exponential via truncated series (no scipy dependency), for small A."""
    R = torch.eye(A.shape[0], dtype=A.dtype)
    term = torch.eye(A.shape[0], dtype=A.dtype)
    for k in range(1, terms):
        term = term @ A / k
        R = R + term
    return R
